### ISSUE TITLE
[BUG] LC Upload to United States 1940 seems broken...

### ISSUE THREAD

**Issue by Onceageordie** [ShammyLevva/FTAnalyzer#128]
7.3.7.7

After upload to LostCousins, a married woman is added as if she wasn't married, with all her maiden name details:

![image](https://user-images.githubusercontent.com/35932839/54914726-865d7c00-4eed-11e9-8230-f438e8c86cb2.png)

SHOULD look like:

![image](https://user-images.githubusercontent.com/35932839/54914779-aee57600-4eed-11e9-981f-03801204fee5.png)

This only seems to happen with the US 1940 census.

**Comment by Onceageordie** [comment]
Just a thought, how does FTA KNOW that she is married? This particular example has no marriage fact, but does show her as "Wife" in the Residence description.

**Comment by ShammyLevva** [comment]
Could be a shared fact?  Without seeing a GEDCOM snipped of that family it’s awfully difficult to tell.

**Comment by Onceageordie** [comment]
ok snippet here:

1 RESI
2 DATE 1940
2 PLAC Marital Status: Married; Relation to Head: Wife/Wilkinsburg, Allegheny, Pennsylvania, USA
2 SOUR @S1511@
3 PAGE Year: 1940; Census Place: Wilkinsburg, Allegheny, Pennsylvania; Roll
4 CONC : m-t0627-03421; Page: 16B; Enumeration District: 2-611
1 FAMS @F28448@
0 @F28448@ FAM
1 WIFE @I14880@

Hope that's enough!

**Comment by ShammyLevva** [comment]
For the full GEDCOM  is that the only info in the @F28448@ FAM record or are there dates and places? 

Asa rule of thumb, the snippet needs to be sufficient so that adding a header and running the snippet through FTAnalyzer would show the same issue. If it can be replicated as a snippet it’s sufficient if it cannot it isn’t sufficient. Hope that makes sense.

**Comment by Onceageordie** [comment]
ok I've .zipped up the family, hope this helps.

[Isabelle Garbutt 1911.zip](https://github.com/ShammyLevva/FTAnalyzer/files/3005058/Isabelle.Garbutt.1911.zip)

**Comment by ShammyLevva** [comment]
Sorry it's taken so long to look at this I've not been updating the program lately due to family health issues.

I've had a look this evening and it appears there is no family fact for Isabelle so the program cannot know when she is married thus it assumes she isn't at time of marriage. You have WIFE on the census but it isn't recorded anywhere other than as a note on the description of the census something that's not a fact so isn't part of her data.

Essentially to get the program to use her married name it would need to know she was married. This is achievable by indicating marriage fact date of BEF 1940. Otherwise it has nothing to go on. So in this instance the program is correctly using the info in the GED file it's just the GED file is missing information that is in the census.
