### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by HistoryDiver** [ShammyLevva/FTAnalyzer#142]
**Version Number problem appears in**
v1.3.0 (Build 54) for Mac

**Describe the bug**
On 'Locations' data all profile data appears mashed in the "Country" column - addresses, years, occupations etc, all crammed together. Other columns (Region/SubRegion/Address/Place) are blank. Addresses also appear in the "GEDCOM Location" column. 

<img width="1417" alt="Screen Shot 2019-06-16 at 09 54 37" src="https://user-images.githubusercontent.com/51875765/59561846-dd6e7b00-901c-11e9-89be-ef35f0de2fee.png">

**Comment by ShammyLevva** [comment]
That's a problem with your data being unstructured. There is little the program can do to work out what you meant if your locations are unstructured. 

However that report does give you a great place to start to fix your locations. 

Locations get split on commas. You don't appear to have any so it can't work out what the locations split is.

**Comment by HistoryDiver** [comment]
Unstructured? It doesn't appear so on Ancestry. Is there a guide to sorting this out?

**Comment by ShammyLevva** [comment]
From the limited info I can see on that screenshot you don't appear to have any delimiters (eg: commas) to separate out the data. Thus it is impossible for the program to determine anything other than the location text. So it puts that text in one field.

If you have commas separating your data eg: Birmingham, Warwick instead of Birmingham Warwick

Also note how inconsistent your locations are
![image](https://user-images.githubusercontent.com/29687786/59562727-355eaf00-9028-11e9-8969-18b29effd9c6.png)

There's not a lot anyone other than yourself can do to tidy that up. Of course you don't need to tidy it up the locations work ok in one field. They just won't be terribly useful in determining countries etc.

**Comment by HistoryDiver** [comment]
Ok, so, as I've only recently started using FTA, the first step is to go over all the entries in my tree to ensure they are formatted exactly the same way, with commas etc. Does this still work with full addresses? Some entries have street and area defined, others just the parish district or town.

**Comment by ShammyLevva** [comment]
Yup you can just separate each part with a comma just as you would when formally addressing an envelope. 

Basically the program needs something to determine when a new part of the address starts. A space is no good because you can have somewhere like 

Buckingham Palace London England

Which is not Buckingham, Palace, London, England but Buckingham Palace, London, England

Note if you have a family history program on your computer you can usually do a search n replace to tidy up locations.
