### ISSUE TITLE
Duplicate Person

### ISSUE THREAD

**Issue by StoPaul** [ShammyLevva/FTAnalyzer#162]
Please consider checking if a child has 2 or more fathers or mothers.  If so, then consider adding the mother/father to the duplicate person list.  I have a Family Tree Maker 2019 child that has 2 fathers and 2 mothers.  In checking further, the extra father/mother turned out to be duplicates.  Thank you.

**Comment by ShammyLevva** [comment]
This would be an additional score to the duplicate person list? Boosting the chance of identifying person as a duplicate?

Was the duplicate parents already the exact same names or were they slightly different?

**Comment by StoPaul** [comment]
Yes this would be an additional score to boost the duplicate identification.  

 

And yes, the duplicate parents had the same exact names but the facts were different for the two pairs.  In this case the same exact names was not sufficient to cause FTA 7.6.3 to be flagged in the duplicates list.

 

Regards,

Paul

**Comment by StoPaul** [comment]
One other point, if a child shows up 2 or more times in the family table there are 2 possibilities, (1) they are duplicates or (2) not a duplicate but has 2 fathers and/or 2 mothers.  The second case is just a mistake in the family tree that needs correcting.
Regards,

**Comment by ShammyLevva** [comment]
It's not as straightforward as it seems the duplicate individual check scores two individuals those individuals wouldn't be the children having more than one parent they would be the parents appearing twice as parents.

Now whilst it's uncommon for children to appear in multiple families as children its extremely common for someone to appear as a husband/wife/partner in a family. eg: multiple marriages, children with multiple partners etc. 

The scoring for duplicates is specifically checking ONE individual against ONE other individual. There's already a shared parents check. The issue here is the parents are DIFFERENT parents (ie: they are different individuals recorded but actually the parents are the same by mistake). So the shared parents check doesn't work as the actual individuals are different.

I may have a solution but I need a GEDCOM snippet of this sort of family to test it with before I can proceed.

**Comment by ShammyLevva** [comment]
Discovered that the filter for duplicated parents were down scoring miss matching parents. Added extra filter for similar names even if different people this should catch the duplicate parents.

Updated in v7.6.4

**Comment by StoPaul** [comment]
Hi Alexander,

 

I agree it’s not as straight forward as it appears, you highlight good points.

 

I have attached a 200K GEDCOM file generated from FTM2019 with 7 families and 23 people.  Some of the children are shown to have 2 biological fathers and/or 2 biological mothers.  There are no people duplicated.  Hope that it helps clarify any further questions.

 

Nice that you spotted the scoring issue for the duplicate parents.

 

Thanks for taking a look at this issue.

 

Regards,

Paul

**Comment by ShammyLevva** [comment]
I believe I may have got a fix in for v7.6.4 out on Microsoft Windows Store tomorrow Tues 14th April hopefully.
