### ISSUE TITLE
[BUG] - Recent list Greyed out

### ISSUE THREAD

**Issue by EmmArrBee** [ShammyLevva/FTAnalyzer#175]
**Version Number problem appears in** 
v7.8.3.0 and earlier (since move to MS Store??)

**Describe the bug**
List of Recent File lost after every point upgrade.

Of itself, this wouldn't be too annoying, but program also fails to remember directory used when previously using File -->  Open GEDCOM File

**To Reproduce**
After a point version upgrade
1. Go to 'File.'
2. Note Recent item is greyed 

**Expected behavior**
List of recent file is retained across a minor version upgrade (since they are relatively frequent.)

**Screenshots**

**Additional context**

**Comment by EmmArrBee** [comment]
Hi Alexander,

So I waited for v8.0.0.0 and as expected (and perhaps not unreasonably), the list of Recent Files was lost.  The location where I load my GEDCOM files from had also been forgotten.  Having navigated to my preferred location and loaded one GEDCOM, I can confirm FTAnalyzer starts to repopulate my Recent Files list and remembers the location where I find my GEDCOM files. This information is clearly being saved as its is retained across multiple loads of the program and and across systems reboots over a number of days.

And then v8..0.1.0 came along and wiped both the list of Recent Files and its recollection of my preferred GEDCOM directory.

Screenshot (1) show v7.8..5.0 with multiple Recent Files which have been remembered across reboots
![Screenshot 2020-08-15 10 40 04-crop](https://user-images.githubusercontent.com/47026383/92953460-a83c1d00-f459-11ea-9dcf-5cda0e3310ae.png)

Screesnhot (2) shows v8.0.0.0 again with multiple Recent Files,
![Screenshot 2020-09-06 18 05 23-crop](https://user-images.githubusercontent.com/47026383/92954017-a030ad00-f45a-11ea-92c4-8c86f5f0db93.png)

Screenshot (3) shows v8.0.1.0 immediately after first load with greyed out Recent Files
![Screenshot 2020-09-09 15 30 24-crop](https://user-images.githubusercontent.com/47026383/92954203-f867af00-f45a-11ea-9def-0772f9008cca.png)

Screenshot (4) again shows v8.0.1.0 immediately after first load with and Open defaulting back to Documents, rather than the last used location.
![Screenshot 2020-09-09 16 18 41-crop](https://user-images.githubusercontent.com/47026383/92954427-57c5bf00-f45b-11ea-91de-d03f5b42a98a.png)

Screenshot (4) really relates to issue #176 which you've closed.... Having now opened a file, my preferred location is again retained, but presumably only until the next point release. 

The lack of the Recent Files list being retained is annoying, but would be more tolerable if I could set my preferred location and have it remembered across point versions.

M

**Comment by ShammyLevva** [comment]
I appreciate it’s annoying, however if the program is not retaining settings across version updates then adding an additional setting is not going to help. As the additional setting will also fail to be preserved across versions. Thus gaining nothing. 

This has all the hallmarks of the Microsoft store installing the program to a different location and that then being treated as a new fresh program each time rather than an upgrade. I really am at a loss as to how to fix this other than suggest trying the release version instead.

**Comment by EmmArrBee** [comment]
Alexander, I'm not aware that the setting I've made via Tools -> Options are being lost between versions. 

Would it not be possible to offer the user the ability set their preferred location via that type of mechanism and default to My Documents is not set??

M

**Comment by ShammyLevva** [comment]
I've checked the settings for recent files and the last directory are getting saved in the same place as every other setting as I say I can add an extra setting but it will get saved in the same place. So it will make absolutely zero difference, thus is utterly pointless me trying.

Please try the release version, instead of the store version.

INI files died when Windows 7 came out and Microsoft tried to separate settings (INI files/registry settings/etc) from program files. Pre-Windows 7 everything got dumped into the program folder. In Windows 7 and after programs were meant to be installed once - and updated when a new version came along. However the day to day files and settings were encouraged to be put in the documents folder or the registry settings.
