### ISSUE TITLE
BC Dates showing as errors

### ISSUE THREAD

**Issue by lshep0921** [ShammyLevva/FTAnalyzer#180]
Version: 7.8.5.0

I have a lot of entries in RootsMagic 7 with BC dates. They seem to work fine in that program, but they all came over in FTAnalyzer as errors. Is there a certain way they should be written to not throw errors?

Thanks,
Lou

**Version Number problem appears in**
You MUST provide this information so I know what the scope of the problem is. Bugs without this info are unlikely to be addressed. 
NB. at no time ever in the history of the app has there been a version called “latest” they all have a version number. eg: v7.2.2.0

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ShammyLevva** [comment]
Can you give me an example GEDCOM snippet with a couple of dates please?

**Comment by lshep0921** [comment]
[CoupleofBCDates.txt](https://github.com/ShammyLevva/FTAnalyzer/files/5013003/CoupleofBCDates.txt)

Here are 2 individuals with birth and death dates in BC
Thanks,
Lou

**Comment by ShammyLevva** [comment]
Thanks for that I can see it should be easy enough to ignore these as errors HOWEVER given the way dates are stored there isn’t much I can do to recognise the date without adding a whole lot of extra processing. Since this is such an extreme case I am simply not minded to put that work into the program for what would be a vanishingly small number of cases. 

I’ll consider adding support to ignore errors but I suspect I’ll need to treat all such dates as UNKNOWN. Dates are held internally as start date/end date. With the lowest start date I can have is 01/01/0001 there is no provision I can see for negative years. Calculations that crossed the non existent zero year would need special treatment. The entirety of the system that deals with lower bound dates would have to change too.

As I say way way WAY too much effort for a situation that would affect one person in 10,000 and even then the vast majority will be the people who think they’ve actually researched that far back rather than real researchers such as yourself. 

So sorry but I won’t be implementing recognition of pre 01/01/0001 dates.

**Comment by ShammyLevva** [comment]
BCE & CE dates now recognised along with their religious equivalents BC & AD.
BCE & BC dates now treated as UNKNOWN as I cannot handle negative years.
