### ISSUE TITLE
The state of Georgia vs the country

### ISSUE THREAD

**Issue by desdamona902** [ShammyLevva/FTAnalyzer#184]
When I choose "Location" and choose "United States", there is no state of Georgia, only all the other states where I have people. Then I found Georgia in the **country** list, with all its counties. Is this a known bug?

Thanks,
Virginia

**Comment by ShammyLevva** [comment]
No it’s not a known bug it’s because there is no way to tell if someone entering Georgia has simply missed off USA and means the state or means the country. 

Sadly many Americans don’t bother having the country as part of the location which is what causes the problem. If the file has Georgia, USA or Georgia, United States then it will appear in the location list as a state. By missing out the country it can’t be auto corrected for that missing country mistake.

**Comment by desdamona902** [comment]
Thanks. I made the change.
