### ISSUE TITLE
[BUG] Reload option dimmed - unable to restore previously loaded GEDCOM file, must re-import instead

### ISSUE THREAD

**Issue by jonsmith1234** [ShammyLevva/FTAnalyzer#185]
v7.8.5.0

Can import GEDCOM file successfully, however, if I close the FTAnalyzer tool, the Reload option is dimmed upon opening the blank tool.  I must re-import the GEDCOM file again.  My GEDCOM has 225,000 names, so importing takes approximately 30 minutes.

**Comment by ShammyLevva** [comment]
Version 8.0.1 is the latest version it has a number of performance improvements for loading speed, so this may help.

I'm not sure what the issue is though, it should update the latest load file so you can quickly load a GEDCOM again but even if that was working if you close the program you do need to reload the data it doesn't retain the data from one load to the next. 

This is working the same as most other programs in Windows eg: Word/Excel etc where when you restart the program you have to load the file you were working on again. 

Can you confirm that other options that are being set are saved between sessions too?

**Comment by jonsmith1234** [comment]
Yes, The other options are being saved.   I thought the reload meant you could save the GEDCOM and not have to re-import it.   Word/Excel let you save a file.   The import is the time consuming step given the size of my GEDCOM.

I will download the latest version and see if the import times improve.

**Comment by ShammyLevva** [comment]
Ah my mistake I misunderstood. Reload not Recent.

Reload allows you to change options and reload the current file re-analyzing it with the new options. So it is greyed out until you change options.

As I say almost every app when you start the app your file isn't loaded you have to click file and load to load it. So yes Word and Excel both require you to load a file you were working on through the file menu. A massive file though will take time to load and reload does nothing for you unless you change options. So it's working as designed.
