### ISSUE TITLE
Incompatible census references for LostCousins upload 

### ISSUE THREAD

**Issue by vmldoran** [ShammyLevva/FTAnalyzer#195]
Version 1.3.0 (54)

I have the Mac version. I build my trees on Ancestry, then download to Family Tree Maker 2019 (24.0.1.252), then create a .ged file and upload to FTAnalyzer. I have successfully then uploaded to LostCousins for 2 of my 4 trees, one of which has over 8,500 people in it.
Have now tried with another large tree. It accepted 29 census references but is listing over 500 events for relevant censuses as having invalid references. All the references have been created by Ancestry and, on inspection look correct to me. I have also tried using a .ged created by Ancestry and get identical results.

What is listed in the 'Census reference' column is actually the street address that I have put in the 'description' field on Ancestry.

Is there a bug, or have I accidentally done something incorrect?

Here are 3 screenshots - the summary showing the number of 'rejected' entries; the first screenful of the 'invalid census references' report - part 1 is the left hand part, part 2 the right hand of the same rows
![summary](https://user-images.githubusercontent.com/76163729/102489106-5369fd00-406d-11eb-8de9-2eafde150ce3.jpg)
![part 1](https://user-images.githubusercontent.com/76163729/102489127-58c74780-406d-11eb-8d66-2eebaef2c48f.jpg)

![part 2](https://user-images.githubusercontent.com/76163729/102489183-6a105400-406d-11eb-8488-dca0c9e4f773.jpg)

Victoria M L Doran

**Comment by ShammyLevva** [comment]
Hi there,

I can't tell anything from the screenshots other than yes the census references are not census references but addresses. I'd need a sample GEDCOM of an individual to see what the problem was. From what you said I suspect the place is in the description field and not in the place field. Maybe the two got mixed up?

**Comment by vmldoran** [comment]
Hi

Many thanks for the speedy response.

Attached should be a GEDCOM for the first line on the screenshot.

Victoria

**Comment by ShammyLevva** [comment]
Ah you need to visit github to attach a file replying to email and it gets stripped.

**Comment by vmldoran** [comment]
Hi

Just tried that but it stated that .ged is not a supported file type for an
attachment.

What do I do now?

Victoria

**Comment by ShammyLevva** [comment]
Rename it to a .txt file or email me at ftanalyzer@gmail.com

**Comment by ShammyLevva** [comment]
Thanks I'd never seen that sort of recording of census reference before. Instead of the reference appearing in the source text with a link it was on the source line.

`1 RESI 46 Frank Street; drainer
2 DATE 1901
2 PLAC Preston, Lancashire, England
2 SOUR Class: RG13; Piece: 3950; Folio: 11; Page: 13.
`
Instead of the line being
`2 SOUR @s1@

to point to source 1 for instance. Fixed in core code. This will appear in Windows version 8.1 and when I get my new PC will eventually appear in the Mac version but that will be well into 2021 as I haven't been able to access the Mac version `on old machine since I had to work from home at start of lockdown. So even when I get new machine (which is waiting on availability of RTX 3080 graphics cards) it will probably take me quite some time to remember how to code things on the Mac. 

That said Mac and Windows share a code base so all these little tweaks are included it's just the Mac has a hideously awful way of designing the UI screens that made development on a Mac a right royal pain. So whilst this issue is fixed please be aware the fix won't appear on the Mac for anywhere between 3 and 9 months.

**Comment by ShammyLevva** [comment]
You may be able to fix this in the tree by checking how sources are recorded. It looks like it's some option to embed sources in the fact rather than creating separate source records.

**Comment by vmldoran** [comment]
Hi

I think it may be a historical issue with Ancestry. I haven't worked on
this part of my tree for many years, and I think the sources were probably
attached c 2011. I haven't had the same problem with my other trees, where
almost all is much more recent work.

I may try deleting a census and re-attaching to see if it makes a
difference. Will let you know if it does, but it would be a lot of work to
do that for all the over 500 entries I have like that.

Many thanks for your speedy responses. It will be no problem to wait for
the Mac fixes.

Does FTA update automatically for fixes, or how will I know to look for
updates?

Victoria

**Comment by ShammyLevva** [comment]
As with most apps in the App Store it should auto update unless you tell it not to.

**Comment by vmldoran** [comment]
Thanks

Victoria

**Comment by vmldoran** [comment]
Hi Again

I removed the 1881 census from James Speariett on Ancestry and searched and found the current version and re-attached it. Then downloaded the same .ged into FTAnalyzer.

He is no longer an error, but the rest of the family on the same census still are.

So it is a historical issue with Ancestry. However many people might be affected by it.

Victoria
