### ISSUE TITLE
Duplicate records in 'Show Places'

### ISSUE THREAD

**Issue by Anorak1032** [ShammyLevva/FTAnalyzer#205]
Version 8.3.0.0

InMaps>Show Places: duplicate records are shown for individuals with a location in more than one country when more than one country is selected.

e.g. Mr Smith has geocoded records for locations in both England and Scotland

If **just** England is selected in Show Places, the correct records for England are shown for Mr Smith. If **just** Scotland is selected in Show Places, the correct records for Scotland are shown for Mr Smith. However, if **both** England and Scotland are selected, **all** of Mr. Smith's records are duplicated.

**Comment by ShammyLevva** [comment]
Thanks for the report. Have you seen if this is the case for any other two countries or is it perhaps UK specific?

**Comment by Anorak1032** [comment]
Hi,

 

Sorry, but I cannot advise further as all of my ancestors have at least one UK geocoded record.

 

Regards,

 

Phil Reid

**Comment by ShammyLevva** [comment]
No problem I wondered if it was say someone had Spain and Scotland that it showed both records duplicated too or whether it was unique to UK countries which have special processing. I'll try to replicate the issue, however it may help if you could provide a mini GEDCOM of a single individual that shows the problem. You can email the file to ftanalyzer@gmail.com that then makes it quicker to diagnose as I have an actual file with an error rather than trying to reproduce the problem I can work on fix instead.

**Comment by ShammyLevva** [comment]
Added check for unique records when building lists.

**Comment by ShammyLevva** [comment]
Fixed in v8.3.1

**Comment by Anorak1032** [comment]
Many thanks for the quick response.

Any idea when v8.3.1 will be released?

 

Phil

**Comment by ShammyLevva** [comment]
There’s a couple of tweaks to other things and I’m awaiting a file from another user. I anticipate it will be out within next few days though.
