### ISSUE TITLE
FTAnalyzer Permissions

### ISSUE THREAD

**Issue by BriGllynn** [ShammyLevva/FTAnalyzer#210]
I am trying use FTAnalyzer on Win10 pc but am receiving the following Error message >
 "Unable to save window permissions please check App has rights to save user preferencies to registry"
How do I resolve this issue please?

**Comment by ShammyLevva** [comment]
This is typically due to a bad install. The program stores settings like recent files etc in the registry if the install didn't correctly setup permissions then the program cannot store settings. Typically this is due to a bug in the Microsoft Store installer. Microsoft have produced a program to fix various windows store errors which is available at http://ftanalyzer.com/ResetWindowsStore

After fixing the store you'd need to uninstall and reinstall. Note the install needs to be done by an account with admin rights so that it can set permissions. Typically the default user has the necessary rights but sometimes this isn't the case. 

As an alternative to the Windows Store if the Store App is simply broken on your machine you can install the release version from www.ftanalyzer.com/releases

**Comment by BriGllynn** [comment]
Great.  Thanks for your prompt reply.  I'll try that later.
BriGllynn

------ Original Message ------
