### ISSUE TITLE
Changing search site

### ISSUE THREAD

**Issue by Pentris** [ShammyLevva/FTAnalyzer#23]
Cannot find any place to change the search site e.g. find my past, ancestry etc. Online manual refers to 'options' in menu bar but this does not include this ability to change the search site. Am using version 6.2.1.0

**Comment by fire-eggs** [comment]
I think you need to get to the census report before you can choose your search site.

E.g. in the Census tab, click on "Show Missing from Census". The report window appears. The dropdown to select among the search sites is at the top of the window.

Screen cap: [older version]
![fta_site_choice](https://user-images.githubusercontent.com/9809727/37245220-e9b1506c-2462-11e8-801b-5a438acfa459.PNG)

**Comment by ShammyLevva** [comment]
Yes on any of the screens that allow auto searching. There’s a dropdown menu that allows you to choose which site it looks up.

**Comment by Pentris** [comment]
Thank you. As the convention is for ‘Options’ to be a selection point in a main screen top level menu bar I found the main menu bar, then Tools, then Options, but it was not there as expected. Thanks for directing me to the correct location in the secondary windows.

Kind regards

Robin Dew

**Comment by Pentris** [comment]
Thank you. As the convention is for ‘Options’ to be a selection point in a main screen top level menu bar I found the main menu bar, then Tools, then Options, but it was not there as expected. Thanks for directing me to the correct location in the secondary windows.

Kind regards

Robin Dew

**Comment by ShammyLevva** [comment]
The convention is that options that are program wide are available on an options or preferences screen. However this is NOT what this feature is. This feature is a switch that allows you to vary which site you want to visit on a per lookup basis. 

It is entirely likely that someone would wish to look up an entry on Ancestry then if they didn’t find something there switch the selection and try a different site. 

Thus because it is an active selection and not an system wide option it would be entirely inappropriate for it to appear on the options menu. Thus despite what you say I stand by its location as being entirely correct.
