### ISSUE TITLE
[BUG] Issues with US Color Census report

### ISSUE THREAD

**Issue by Ann1k3n** [ShammyLevva/FTAnalyzer#233]
**Version Number problem appears in**
v. 8.3.1.0

**Describe the bug**
I'm using the US Color census report and getting some unexpected (on my part) behavior. Looking for suggestions. Two people in the attached GEDCOM were born in a census year after the census day. They don't appear on the census, but FTA shows a red box on the color census report. One person died the year prior to the census and doesn't appear on the census, but shows a red box for that census year. One person immigrated to the US in 1884 (arrival fact), but shows a red box for the 1880 census. Also, Lost Cousins hates my 1880 citations (but happily accepts my 1940 citations).

**To Reproduce**
1. Go to Research Suggestions tab
2. Click on View US Color Census Report with all relationship type boxes checked.

**Expected behavior**
I'm not sure these are technically bugs. I just want to understand how to input my data to clean up the report if possible. I really love the color census report, and find it very helpful for tracking down missing census items.
I expect to see light gray boxes on the color census report for years when the person is not alive to be in the census. I expect to see dark gray boxes on the color census report for years in which the person is not in the correct country to be in the census.

**Additional context**
I use Family Tree Maker 2019 on a Windows machine (v. 24.0.1.1252). Probably FTM doesn't make the cleanest GEDCOMs, which may be contributing to my issues.
[Tracie's Tree_2021-09-09_FTA Test.ged.txt](https://github.com/ShammyLevva/FTAnalyzer/files/7140032/Tracie.s.Tree_2021-09-09_FTA.Test.ged.txt)

**Comment by ShammyLevva** [comment]
As mentioned on Facebook user group the issue is around the US Census dates being a wide range of dates. So the person was potentially alive during the active period of the census so a grey box would just be wrong. That said the fact their birth/death overlaps the census date suggests that some form of different highlighting would be useful.

One problem is that dates like a death of BEF 1885 would overlap census dates prior to 1885. So a simple overlaps census date check isn’t going to work, it will need to be more subtle than that. It also can’t just be a check for exact dates as a date of Mar 1880 is not exact but is overlapping to. 

Maybe it has to be died or born DURING census period? Ie: not just overlap but start and end date of event covered by census date range. I’d need to give it more thought.

**Comment by Ann1k3n** [comment]
Yes, I saw your explanation on the FB user guide. I appreciate you taking the time to respond and agree that the grey box would be incorrect in this case. I guess the red box makes me feel like I need to fix it, but there's nothing to fix (at least in the particular cases where I was seeing the issue).

**Comment by ShammyLevva** [comment]
I think it still makes sense to investigate if there are circumstances that would work where the icon should show a different colour to highlight a questionable status. 

I think the issue is that due to the census date for some US census stretching over a 14+ month period it’s possible someone who died in the period did appear on the census it’s equally possible they didn’t. The red warning does seem harsh though.

**Comment by ShammyLevva** [comment]
Added pink colour to show died within range of dates that census was taken so may or may not be alive during census period in area he lived. This is available in v8.5.0 when released.
