### ISSUE TITLE
No Sliders

### ISSUE THREAD

**Issue by gafii** [ShammyLevva/FTAnalyzer#277]
**Version Number problem appears in**
You MUST provide this information so I know what the scope of the problem is. Bugs without this info are unlikely to be addressed. 
NB. at no time ever in the history of the app has there been a version called “latest” they all have a version number. eg: v7.2.2.0

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by gafii** [comment]
Can not see all of data because there are no sliders to move to right.  Attached file shows inability to access all info
[Fam tree analyser.pdf](https://github.com/ShammyLevva/FTAnalyzer/files/10474098/Fam.tree.analyser.pdf)

**Comment by ShammyLevva** [comment]
This is a known issue with some installs of .Net Framework and certain screen resolutions. Make sure you are running .Net Framework 4.8 or adjust the resolution this is a bug in the .Net Framework that Microsoft has acknowledged but since they are moving people to .Net 6.0 they aren't going to fix it. 

v10 of FTAnalyzer runs on .Net 6. https://github.com/ShammyLevva/FTAnalyzer/releases

Since it's a bug in the underlying framework it is not something I can fix.

**Comment by gafii** [comment]
I do not have .NET on my Win 10 installation.  I adjusted the resolution, but I still could not scroll to the right.  The attached screen shot shows my display.  I can not go any further to the right of what is shown.

**Comment by gafii** [comment]
My apologies. I have .NET 3.5

**Comment by gafii** [comment]
Again my apologies, but version 4.8 is installed.

**Comment by ShammyLevva** [comment]
> My apologies. I have .NET 3.5

This is likely to be causing issues .Net 3.5 was deprecated along with Windows 7 three years ago. You really shoudn't be relying on any ancient apps that use .Net 3.5. Even .Net 4.8 is now reaching end of life and due to be replaced by .Net 6. 

I CANNOT fix a problem that is in the core Microsoft code.
