### ISSUE TITLE
[BUG] Vertical scrollbar on "Main Lists" page

### ISSUE THREAD

**Issue by davejbur** [ShammyLevva/FTAnalyzer#299]
**Version Number problem appears in**
8.1.2

**Describe the bug**
No scrollbar visible on "Main Lists" tab.

**To Reproduce**
1. Open FTA
2. Import GEDCOM (one with more people than would fit on one page at your current screen resolution - say >50 to be on the safe side)
3. Got to "Main Lists" tab
4. No vertical scrollbar visible at right hand end

**Expected behavior**
A vertical scrollbar, as is visible in prior versions up to & including 8.1.1.0

**Screenshots**
8.1.1.0:
![image](https://github.com/ShammyLevva/FTAnalyzer/assets/12410619/c042226d-7d0d-405a-a847-ee31d09bbd52)

8.1.2:
![image](https://github.com/ShammyLevva/FTAnalyzer/assets/12410619/962a9b8e-4b70-4597-82da-67bbe917ac07)

**Additional context**
Still not visible in 8.5.2.

**Comment by ShammyLevva** [comment]
It’s not the version that’s the issue it varies according to screen resolution and font size settings. It appears to be a bug in the .net framework 4.8 which is deprecated. I’ve never been able to reliably replicate the issue as it seems transitory. The vast majority of people don’t have the issue a few have but I’ve not been able to find common settings to replicate it. If I can’t see it happening I can’t know if I’ve fixed it. 

Since 4.8 is no longer actively developed I’ve moved the project onto the .Net 6 platform which is supported going forward on all up to date Windows platforms. There is a beta in the releases area if you want to try that.

**Comment by ShammyLevva** [comment]
Added forcing code to try to ensure scrollbars always visible. Updated for v10.0.0.0-beta4
