### ISSUE TITLE
Importing GEDcom now fails with error "error NEVER MARRIED text in non death fact"

### ISSUE THREAD

**Issue by UncleBuck62** [ShammyLevva/FTAnalyzer#44]
**Describe the bug**
Exporting a gedcom from FTM allows you to have a date of "never married" for a marriage date. The previous versions of FTA used to allow the import of the file and just reported an error, however, now the whole import fails and reports the error.

**To Reproduce**
Import any gedcom that has been exported from FTM that has a marriage date of "never married"

**Expected behavior**
The file should still import and show the import errors (as it did in the previous versions), not prevent the whole file from being imported.

**Screenshots**
Not required in this case as the error is obvious

**Desktop (please complete the following information):**
 FTM running on MAC OSX 10.11.6
FTA running on Windows 7 under virtual box.

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by ShammyLevva** [comment]
For clarity this Never Married is entered as a Marriage date fact even though the person has no spouse? Doesn’t this create a blank spouse for that person too?

I’ve not been able to exactly reproduce this so a sample GEDCOM export of one individual that has this fact would show me exactly where the program is going wrong and enable me to fix it. 

The never married support was added very recently so that may be the cause. However I’d been led to understand it was only valid as a personal fact not a shared fact so if I’m understanding you correctly that will be the issue. 

A test file of a single individual with this data would prove that. I’ll be able to fix this when I get up on Saturday and release a new version so you can get back working if you can supply the file.

**Comment by fire-eggs** [comment]
I was able to repro the problem. In my case, the GED file had a FAM record with a MARR fact whose DATE was "Never married".

See attached: FAM record @F129@ starting at line 90346.
[Scalf.zip](https://github.com/ShammyLevva/FTAnalyzer/files/2545242/Scalf.zip)

Sorry for large file, first one I found. Note it is PAF, I'm not sure if/how FTM might do it differently.

**Comment by ShammyLevva** [comment]
Fixed for next version. Thanks.
