### ISSUE TITLE
[BUG] Missing error facts

### ISSUE THREAD

**Issue by ShammyLevva** [ShammyLevva/FTAnalyzer#78]
**Version Number problem appears in**
v7.3.0.0-beta 12

There is an error condition called Fact Error/Warning but it's not showing any errors even though some exist I suspect errors aren't tagged with that error class. so that one needs special treatment.

**Comment by Phantomsteve2001** [comment]
I am getting Error/Warning, but it's doing it correctly:

![image](https://user-images.githubusercontent.com/46846498/51429017-2bb05700-1c02-11e9-9e85-c6f034120073.png)

The first person is clearly dead before 1940 anyway, so it makes even less sense on that one!

James Lockhart Ashton Census Facts are:
- CENSUS: 1881 [Preferred]
- CENSUS: 1891 [Alternate]
- CENSUS: 1901 [Alternate]
- CENSUS: 1911 [Alternate]

Robert has 1881 as preferred, 1891 as alternate; Jane has the same; as does Thomas.

The only thing that I think may be confusing matters is that these are all in Scotland for those census, rather than England.

Looking at all of the other Scotland residents in my GEDCOM, then either they have no CENSUS facts, or they have only 1 - i.e. this only seems to affect those who are recorded on a Scottish Census, and where there are alternate census facts.

**Comment by Phantomsteve2001** [comment]
![image](https://user-images.githubusercontent.com/46846498/51429672-d3c91e80-1c08-11e9-8f95-1a089b03e08f.png)

I don't know where it got the 1940 from at all... the census info, reference, etc all say 1881, with no mention of 1940

**Comment by Phantomsteve2001** [comment]
Also, when I look at the GEDCOM section, and isolate just James Lockhart Ashton (from 0 @I171@ INDI
1 NAME James Lockhart /ASHTON/ ... down to the next INDI entry for his father), the text "1940" does not appear at all.

[James Ashton GEDCOM.txt](https://github.com/ShammyLevva/FTAnalyzer/files/2775754/James.Ashton.GEDCOM.txt)

**Comment by ShammyLevva** [comment]
Cheers I'll close this issue and re-open the issue that i raised as it was very different to the issue you raised.
