### ISSUE TITLE
[BUG] Lost Cousin update count inconsistencies

### ISSUE THREAD

**Issue by bmurcutt** [ShammyLevva/FTAnalyzer#97]
Version 7.3.6.0

I did a Lost Cousins update today, with FTAnalyzer recording the following counts:

Census                   Failed to Load | Already Present | Added

EW 1881                                  18                   261          204
EW 1841                                  11                       3            80
EW 1911                                    8                     49          169
US 1940                                   21                       0             0

Totals                                       58                   313          453
  
Total possible records:  824 - this matched the count on the upload screen before update

 I then checked Lost Cousins:

1881 - +184 (discrepancy 20)
1841 - +  80 (ok)
1911 - +162 (discrepancy 7)
1940 - +    0 (ok)

Total:  426 (total discrepancy 27)

Do you have any explanation before I endeavour to try and go through line by line to try and find inconsistent transactions and identify possible causes?

It might also be useful to know the location of the file where you record your lost cousin 'already loaded' details (so you don't try and load again - assuming it is accessible to us and is 'readable').

FYI - I will try (later on) to work through the 'failed to load' records, though on the surface they mostly appear to be either where the 'Book' is not valid (refer recent issues with 1841 coding), where I don't have a maiden name for a spouse (and I default it to [--- ? ---]), or are 1940 US records.  But a handful do look like they should be ok … ???

Thanks.

**Comment by ShammyLevva** [comment]
I spotted an issue whilst dealing with issue #95 you raised. Where by unknown family types weren't being processed correctly and showed up as invalid references when they weren't.

I'm therefore not sure if this is still issue would have been fixed by this or not.

ie: having fixed #95 I looked at the Lost Cousins report and was surprised to find the now good fact wasn't showing up at all. It turned out that the test individual family type was set as unknown and that wasn't being processed correctly. So that bug was fixed as part of dealing with #95 

What I'll do is release a new version so you can re-check the figures and see if they have improved. If not it would be really useful if you could somehow manage to narrow down a sample GEDCOM to invalid individuals. Failing that I could investigate from your GEDCOM file that has the full set of discrepancies.

So if we put this one on hold until you've had a chance to test new version.

**Comment by ShammyLevva** [comment]
Looks like this is down to census refs reports not using the filters unlike the census reports. Reworked the reports to use filters.

**Comment by ShammyLevva** [comment]
Deleted previous comments as not relevant.

**Comment by ShammyLevva** [comment]
You should only ever get already presents if you have manually entered data to Lost Cousins and not recorded a lost cousins fact. 

Note this might have happened if you upload the data when the SQL error bug was on the go. 

What should happen and will have happened this time (I Hope) is that it will have created a Lost cousins fact and stored that in the geocodes database. The database is saved at %appdata%\Family Tree Analyzer. You can view it using a SQLite database browser. I’d suggest SQLiteStudio 
https://sqlitestudio.pl/index.rvt

What that database does is re-create the Lost cousins fact when you next load your file. So that the lost cousins report tab should show lots of entered facts and the facts tab should show lost cousins facts. 

This should mean that the numbers it shows as “missing” from Lost Cousins goes down to zero after an upload (barring erroring records).

**Comment by ShammyLevva** [comment]
The failed to load should be zero. If not then I’m trying to save data that’s getting rejected and I need to fix the reason for the bad upload. 

As for discrepancies in the count this will very likely be down to a record getting sent and no error being reported but not actually getting updated as it was already present and the already present code failed to detect that. 

Sadly the lost cousins website is really quite antiquated and simply silently fails in those circumstances. Ie there is no success report on an upload the website just goes back to the data entry screen so I have no way of telling if it was successful or it it ignored a duplicate record.

**Comment by bmurcutt** [comment]
Thanks.  One 'guess' I had was that there was still a miscoding on setting 'Book' for 1841 somewhere and while it triggered a 'good' result what you send through isn't valid.  But I haven't looked in detail to see what scenario might be triggering it (yet).

I am just hoping that all of what was sent through and recorded as 'added' did actually update LC (the 824 updates that I sent through took 20-odd minutes to process) - otherwise I will need to figure out how to 'reset' things.

This is where a 'delete load from LC' function would be useful - so loads can be readily retested.  :)

I guess I could delete the 'geocodes' database and they should (in theory) all be able to be reprocessed - just getting a lot more 'already present' outcomes rather than 'added'??   Can I safely do that, or is there other detail in the database that will trip me up somewhere?

**Comment by bmurcutt** [comment]
FYI - reloaded the same GEDCOM, and instead of 58 records still to be loaded to LC (the 'failures' from the last run), there are only 35!!  Curious - still on 7.3.6.0!!

**Comment by ShammyLevva** [comment]
If you delete the contents of the LostCousins table in the geocodes database (leave the actual table intact) then it would attempt to retry them all which should largely result in a lot of already entered records. SQLite Studio will allow you to do this. Failing that deleting the database file would cause the empty database file to be installed on next run.

I've added a couple of tweaks to a) round ages to 5 years in 1841. b) warn if birthdate is too wide a range to accurately determine census age.

The output from the upload process should list every census reference it tried so it should be possible to see any "bad books" from 1841 that slipped through.

**Comment by ShammyLevva** [comment]
BTW will email you with an update.

**Comment by ShammyLevva** [comment]
I think we dealt with this one and I just haven't closed it. Let me know if I'm wrong and i'll reopen.

**Comment by bmurcutt** [comment]
Agree.  Please close.
